### ISSUE TITLE
various docstrings refer to old salt invocations

### ISSUE THREAD

**Issue by tserong** [oms4suse/python-ceph-cfg#13]
Various docstrings (e.g. https://github.com/oms4suse/python-ceph-cfg/blob/master/ceph_cfg/mon.py#L86-L102) have examples like `salt '*' sesceph.keys_create`. These should probably be removed or updated, as this library is intended to be usable without salt.

**Comment by oms4suse** [comment]
I now have a PR for this https://github.com/oms4suse/python-ceph-cfg/pull/21

**Comment by oms4suse** [comment]
Now resolved in master and latest release. Thanks Tim.
